[package]
name = "kruste"
version = "0.2.0"
edition = "2024"
license = "MIT"
authors = ["YooTrickFrame/lce2011"]

[dependencies]
color-eyre = "0.6.5"
crossterm = "0.29.0"
ratatui = "0.30.2"
ratatui-textarea = "0.9.2"
serde = { version = "1.0.229", features = ["derive"] }
serde_json = "1.0.151"

[profile.dev]
opt-level = 1
debug = true
codegen-units = 256

[profile.dev.package."*"]
opt-level = 2

[profile.release]
opt-level = 3
lto = "thin"
codegen-units = 1
strip = true
panic = "abort"